# Generated by Django 2.2.4 on 2021-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sapid', models.CharField(blank=True, max_length=18, null=True)),
                ('hostname', models.CharField(blank=True, max_length=14, null=True)),
                ('loopback', models.CharField(blank=True, max_length=16, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
            ],
        ),
    ]
