# Generated by Django 2.2.4 on 2021-02-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0002_device_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='loopback',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
